<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logger/options.proto

namespace Logger;

use UnexpectedValueException;

/**
 * Protobuf type <code>logger.Sensitivity</code>
 */
class Sensitivity
{
    /**
     * Unannotated default — safe to log.
     * Identifiers, IDs, timestamps, enums, status fields.
     *
     * Generated from protobuf enum <code>SENSITIVITY_UNSPECIFIED = 0;</code>
     */
    const SENSITIVITY_UNSPECIFIED = 0;
    /**
     * User-identifying or user-controlled data: display names, phone numbers,
     * metadata, attributes, custom headers, auth usernames, semi-public account
     * identifiers (AWS role ARNs, Azure account names).
     * Redacted by logger.Proto(); exposed by logger.UnredactedProto() for
     * operator-facing observability events.
     *
     * Generated from protobuf enum <code>SENSITIVITY_PII = 1;</code>
     */
    const SENSITIVITY_PII = 1;
    /**
     * Credentials and authentication material: passwords, access keys, session
     * tokens, signing keys, API keys, ICE credentials.
     * ALWAYS redacted, including by logger.UnredactedProto().
     *
     * Generated from protobuf enum <code>SENSITIVITY_SECRET = 2;</code>
     */
    const SENSITIVITY_SECRET = 2;

    private static $valueToName = [
        self::SENSITIVITY_UNSPECIFIED => 'SENSITIVITY_UNSPECIFIED',
        self::SENSITIVITY_PII => 'SENSITIVITY_PII',
        self::SENSITIVITY_SECRET => 'SENSITIVITY_SECRET',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

