<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT! (protoc-gen-twirp_php 0.15.0)
# source: livekit_agent_simulation.proto

declare(strict_types=1);

namespace Livekit;

/**
 *
 *
 * Generated from protobuf service <code>livekit.AgentSimulation</code>
 */
interface AgentSimulation
{
    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateSimulationRun(array $ctx, \Livekit\SimulationRun\Create\Request $req): \Livekit\SimulationRun\Create\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ConfirmSimulationSourceUpload</code>
     *
     * @throws \Twirp\Error
     */
    public function ConfirmSimulationSourceUpload(array $ctx, \Livekit\SimulationRun\ConfirmSourceUpload\Request $req): \Livekit\SimulationRun\ConfirmSourceUpload\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/GetSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function GetSimulationRun(array $ctx, \Livekit\SimulationRun\Get\Request $req): \Livekit\SimulationRun\Get\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/ListSimulationRuns</code>
     *
     * @throws \Twirp\Error
     */
    public function ListSimulationRuns(array $ctx, \Livekit\SimulationRun\PBList\Request $req): \Livekit\SimulationRun\PBList\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CancelSimulationRun</code>
     *
     * @throws \Twirp\Error
     */
    public function CancelSimulationRun(array $ctx, \Livekit\SimulationRun\Cancel\Request $req): \Livekit\SimulationRun\Cancel\Response;

    /**
     *
     *
     * Generated from protobuf method <code>livekit.AgentSimulation/CreateScenarioFromSession</code>
     *
     * @throws \Twirp\Error
     */
    public function CreateScenarioFromSession(array $ctx, \Livekit\Scenario\CreateFromSession\Request $req): \Livekit\Scenario\CreateFromSession\Response;
}
