<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\ClientInfo\Capability instead.
     * @deprecated
     */
    class ClientInfo_Capability {}
}
class_exists(ClientInfo\Capability::class);
@trigger_error('Livekit\ClientInfo_Capability is deprecated and will be removed in the next major release. Use Livekit\ClientInfo\Capability instead', E_USER_DEPRECATED);

