<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_cloud_agent.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\CreatePrivateLinkRequest\AWSCreateConfig instead.
     * @deprecated
     */
    class CreatePrivateLinkRequest_AWSCreateConfig {}
}
class_exists(CreatePrivateLinkRequest\AWSCreateConfig::class);
@trigger_error('Livekit\CreatePrivateLinkRequest_AWSCreateConfig is deprecated and will be removed in the next major release. Use Livekit\CreatePrivateLinkRequest\AWSCreateConfig instead', E_USER_DEPRECATED);

