<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\DataTrackFrameEncoding\WellKnownFrameEncoding instead.
     * @deprecated
     */
    class DataTrackFrameEncoding_WellKnownFrameEncoding {}
}
class_exists(DataTrackFrameEncoding\WellKnownFrameEncoding::class);
@trigger_error('Livekit\DataTrackFrameEncoding_WellKnownFrameEncoding is deprecated and will be removed in the next major release. Use Livekit\DataTrackFrameEncoding\WellKnownFrameEncoding instead', E_USER_DEPRECATED);

