<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\DataTrackSchemaEncoding\WellKnownSchemaEncoding instead.
     * @deprecated
     */
    class DataTrackSchemaEncoding_WellKnownSchemaEncoding {}
}
class_exists(DataTrackSchemaEncoding\WellKnownSchemaEncoding::class);
@trigger_error('Livekit\DataTrackSchemaEncoding_WellKnownSchemaEncoding is deprecated and will be removed in the next major release. Use Livekit\DataTrackSchemaEncoding\WellKnownSchemaEncoding instead', E_USER_DEPRECATED);

