<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_models.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\DataStream\CompressionType instead.
     * @deprecated
     */
    class DataStream_CompressionType {}
}
class_exists(DataStream\CompressionType::class);
@trigger_error('Livekit\DataStream_CompressionType is deprecated and will be removed in the next major release. Use Livekit\DataStream\CompressionType instead', E_USER_DEPRECATED);

