<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_cloud_agent.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\PrivateLink\AWSConfig instead.
     * @deprecated
     */
    class PrivateLink_AWSConfig {}
}
class_exists(PrivateLink\AWSConfig::class);
@trigger_error('Livekit\PrivateLink_AWSConfig is deprecated and will be removed in the next major release. Use Livekit\PrivateLink\AWSConfig instead', E_USER_DEPRECATED);

