<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_cloud_agent.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\PrivateLinkStatus\Status instead.
     * @deprecated
     */
    class PrivateLinkStatus_Status {}
}
class_exists(PrivateLinkStatus\Status::class);
@trigger_error('Livekit\PrivateLinkStatus_Status is deprecated and will be removed in the next major release. Use Livekit\PrivateLinkStatus\Status instead', E_USER_DEPRECATED);

