<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\RunMetrics instead.
     * @deprecated
     */
    class SimulationRun_RunMetrics {}
}
class_exists(SimulationRun\RunMetrics::class);
@trigger_error('Livekit\SimulationRun_RunMetrics is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\RunMetrics instead', E_USER_DEPRECATED);

