<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\JobMetrics\STT instead.
     * @deprecated
     */
    class SimulationRun_JobMetrics_STT {}
}
class_exists(SimulationRun\JobMetrics\STT::class);
@trigger_error('Livekit\SimulationRun_JobMetrics_STT is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\JobMetrics\STT instead', E_USER_DEPRECATED);

