<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\JobMetrics\TTS instead.
     * @deprecated
     */
    class SimulationRun_JobMetrics_TTS {}
}
class_exists(SimulationRun\JobMetrics\TTS::class);
@trigger_error('Livekit\SimulationRun_JobMetrics_TTS is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\JobMetrics\TTS instead', E_USER_DEPRECATED);

