<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\Usage instead.
     * @deprecated
     */
    class SimulationRun_Usage {}
}
class_exists(SimulationRun\Usage::class);
@trigger_error('Livekit\SimulationRun_Usage is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\Usage instead', E_USER_DEPRECATED);

