<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\JobMetrics\Conversation instead.
     * @deprecated
     */
    class SimulationRun_JobMetrics_Conversation {}
}
class_exists(SimulationRun\JobMetrics\Conversation::class);
@trigger_error('Livekit\SimulationRun_JobMetrics_Conversation is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\JobMetrics\Conversation instead', E_USER_DEPRECATED);

