<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\JobMetrics\Simulator instead.
     * @deprecated
     */
    class SimulationRun_JobMetrics_Simulator {}
}
class_exists(SimulationRun\JobMetrics\Simulator::class);
@trigger_error('Livekit\SimulationRun_JobMetrics_Simulator is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\JobMetrics\Simulator instead', E_USER_DEPRECATED);

