<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit;

if (false) {
    /**
     * This class is deprecated. Use Livekit\SimulationRun\Job\Usage instead.
     * @deprecated
     */
    class SimulationRun_Job_Usage {}
}
class_exists(SimulationRun\Job\Usage::class);
@trigger_error('Livekit\SimulationRun_Job_Usage is deprecated and will be removed in the next major release. Use Livekit\SimulationRun\Job\Usage instead', E_USER_DEPRECATED);

