<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit\SimulationRun\JobMetrics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The agent's voice. audio only.
 *
 * Generated from protobuf message <code>livekit.SimulationRun.JobMetrics.TTS</code>
 */
class TTS extends \Google\Protobuf\Internal\Message
{
    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 ttfa_ms = 1;</code>
     */
    protected $ttfa_ms = null;
    /**
     * needs the RemoteSession; provider byte-level TTFB
     *
     * Generated from protobuf field <code>optional uint32 ttfb_ms = 2;</code>
     */
    protected $ttfb_ms = null;
    /**
     * needs the RemoteSession; word error rate, pooled: word_errors / words
     *
     * Generated from protobuf field <code>optional float wer = 3;</code>
     */
    protected $wer = null;
    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 words = 7;</code>
     */
    protected $words = null;
    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 word_errors = 8;</code>
     */
    protected $word_errors = null;
    /**
     * needs the RemoteSession; character error rate, pooled
     *
     * Generated from protobuf field <code>optional float cer = 9;</code>
     */
    protected $cer = null;
    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 chars = 10;</code>
     */
    protected $chars = null;
    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 char_errors = 11;</code>
     */
    protected $char_errors = null;
    /**
     * speaking rate; conversational English ~110-150
     *
     * Generated from protobuf field <code>optional float speech_rate_wpm = 4;</code>
     */
    protected $speech_rate_wpm = null;
    /**
     * pooling stats for speech_rate_wpm: raw heard words (not WER tokens)
     *
     * Generated from protobuf field <code>optional uint32 heard_words = 12;</code>
     */
    protected $heard_words = null;
    /**
     * agent voiced time, sum of raw VAD segments
     *
     * Generated from protobuf field <code>optional uint32 speech_ms = 13;</code>
     */
    protected $speech_ms = null;
    /**
     * needs the audio judge; judged 0-1: prosody / expressiveness
     *
     * Generated from protobuf field <code>optional float naturalness_score = 5;</code>
     */
    protected $naturalness_score = null;
    /**
     * needs the audio judge; judged 0-1: key entities audibly intact
     *
     * Generated from protobuf field <code>optional float enunciation_score = 6;</code>
     */
    protected $enunciation_score = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ttfa_ms
     *           needs the RemoteSession
     *     @type int $ttfb_ms
     *           needs the RemoteSession; provider byte-level TTFB
     *     @type float $wer
     *           needs the RemoteSession; word error rate, pooled: word_errors / words
     *     @type int $words
     *           needs the RemoteSession
     *     @type int $word_errors
     *           needs the RemoteSession
     *     @type float $cer
     *           needs the RemoteSession; character error rate, pooled
     *     @type int $chars
     *           needs the RemoteSession
     *     @type int $char_errors
     *           needs the RemoteSession
     *     @type float $speech_rate_wpm
     *           speaking rate; conversational English ~110-150
     *     @type int $heard_words
     *           pooling stats for speech_rate_wpm: raw heard words (not WER tokens)
     *     @type int $speech_ms
     *           agent voiced time, sum of raw VAD segments
     *     @type float $naturalness_score
     *           needs the audio judge; judged 0-1: prosody / expressiveness
     *     @type float $enunciation_score
     *           needs the audio judge; judged 0-1: key entities audibly intact
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAgentSimulation::initOnce();
        parent::__construct($data);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 ttfa_ms = 1;</code>
     * @return int
     */
    public function getTtfaMs()
    {
        return isset($this->ttfa_ms) ? $this->ttfa_ms : 0;
    }

    public function hasTtfaMs()
    {
        return isset($this->ttfa_ms);
    }

    public function clearTtfaMs()
    {
        unset($this->ttfa_ms);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 ttfa_ms = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTtfaMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->ttfa_ms = $var;

        return $this;
    }

    /**
     * needs the RemoteSession; provider byte-level TTFB
     *
     * Generated from protobuf field <code>optional uint32 ttfb_ms = 2;</code>
     * @return int
     */
    public function getTtfbMs()
    {
        return isset($this->ttfb_ms) ? $this->ttfb_ms : 0;
    }

    public function hasTtfbMs()
    {
        return isset($this->ttfb_ms);
    }

    public function clearTtfbMs()
    {
        unset($this->ttfb_ms);
    }

    /**
     * needs the RemoteSession; provider byte-level TTFB
     *
     * Generated from protobuf field <code>optional uint32 ttfb_ms = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTtfbMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->ttfb_ms = $var;

        return $this;
    }

    /**
     * needs the RemoteSession; word error rate, pooled: word_errors / words
     *
     * Generated from protobuf field <code>optional float wer = 3;</code>
     * @return float
     */
    public function getWer()
    {
        return isset($this->wer) ? $this->wer : 0.0;
    }

    public function hasWer()
    {
        return isset($this->wer);
    }

    public function clearWer()
    {
        unset($this->wer);
    }

    /**
     * needs the RemoteSession; word error rate, pooled: word_errors / words
     *
     * Generated from protobuf field <code>optional float wer = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setWer($var)
    {
        GPBUtil::checkFloat($var);
        $this->wer = $var;

        return $this;
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 words = 7;</code>
     * @return int
     */
    public function getWords()
    {
        return isset($this->words) ? $this->words : 0;
    }

    public function hasWords()
    {
        return isset($this->words);
    }

    public function clearWords()
    {
        unset($this->words);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 words = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setWords($var)
    {
        GPBUtil::checkUint32($var);
        $this->words = $var;

        return $this;
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 word_errors = 8;</code>
     * @return int
     */
    public function getWordErrors()
    {
        return isset($this->word_errors) ? $this->word_errors : 0;
    }

    public function hasWordErrors()
    {
        return isset($this->word_errors);
    }

    public function clearWordErrors()
    {
        unset($this->word_errors);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 word_errors = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setWordErrors($var)
    {
        GPBUtil::checkUint32($var);
        $this->word_errors = $var;

        return $this;
    }

    /**
     * needs the RemoteSession; character error rate, pooled
     *
     * Generated from protobuf field <code>optional float cer = 9;</code>
     * @return float
     */
    public function getCer()
    {
        return isset($this->cer) ? $this->cer : 0.0;
    }

    public function hasCer()
    {
        return isset($this->cer);
    }

    public function clearCer()
    {
        unset($this->cer);
    }

    /**
     * needs the RemoteSession; character error rate, pooled
     *
     * Generated from protobuf field <code>optional float cer = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setCer($var)
    {
        GPBUtil::checkFloat($var);
        $this->cer = $var;

        return $this;
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 chars = 10;</code>
     * @return int
     */
    public function getChars()
    {
        return isset($this->chars) ? $this->chars : 0;
    }

    public function hasChars()
    {
        return isset($this->chars);
    }

    public function clearChars()
    {
        unset($this->chars);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 chars = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setChars($var)
    {
        GPBUtil::checkUint32($var);
        $this->chars = $var;

        return $this;
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 char_errors = 11;</code>
     * @return int
     */
    public function getCharErrors()
    {
        return isset($this->char_errors) ? $this->char_errors : 0;
    }

    public function hasCharErrors()
    {
        return isset($this->char_errors);
    }

    public function clearCharErrors()
    {
        unset($this->char_errors);
    }

    /**
     * needs the RemoteSession
     *
     * Generated from protobuf field <code>optional uint32 char_errors = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setCharErrors($var)
    {
        GPBUtil::checkUint32($var);
        $this->char_errors = $var;

        return $this;
    }

    /**
     * speaking rate; conversational English ~110-150
     *
     * Generated from protobuf field <code>optional float speech_rate_wpm = 4;</code>
     * @return float
     */
    public function getSpeechRateWpm()
    {
        return isset($this->speech_rate_wpm) ? $this->speech_rate_wpm : 0.0;
    }

    public function hasSpeechRateWpm()
    {
        return isset($this->speech_rate_wpm);
    }

    public function clearSpeechRateWpm()
    {
        unset($this->speech_rate_wpm);
    }

    /**
     * speaking rate; conversational English ~110-150
     *
     * Generated from protobuf field <code>optional float speech_rate_wpm = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setSpeechRateWpm($var)
    {
        GPBUtil::checkFloat($var);
        $this->speech_rate_wpm = $var;

        return $this;
    }

    /**
     * pooling stats for speech_rate_wpm: raw heard words (not WER tokens)
     *
     * Generated from protobuf field <code>optional uint32 heard_words = 12;</code>
     * @return int
     */
    public function getHeardWords()
    {
        return isset($this->heard_words) ? $this->heard_words : 0;
    }

    public function hasHeardWords()
    {
        return isset($this->heard_words);
    }

    public function clearHeardWords()
    {
        unset($this->heard_words);
    }

    /**
     * pooling stats for speech_rate_wpm: raw heard words (not WER tokens)
     *
     * Generated from protobuf field <code>optional uint32 heard_words = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setHeardWords($var)
    {
        GPBUtil::checkUint32($var);
        $this->heard_words = $var;

        return $this;
    }

    /**
     * agent voiced time, sum of raw VAD segments
     *
     * Generated from protobuf field <code>optional uint32 speech_ms = 13;</code>
     * @return int
     */
    public function getSpeechMs()
    {
        return isset($this->speech_ms) ? $this->speech_ms : 0;
    }

    public function hasSpeechMs()
    {
        return isset($this->speech_ms);
    }

    public function clearSpeechMs()
    {
        unset($this->speech_ms);
    }

    /**
     * agent voiced time, sum of raw VAD segments
     *
     * Generated from protobuf field <code>optional uint32 speech_ms = 13;</code>
     * @param int $var
     * @return $this
     */
    public function setSpeechMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->speech_ms = $var;

        return $this;
    }

    /**
     * needs the audio judge; judged 0-1: prosody / expressiveness
     *
     * Generated from protobuf field <code>optional float naturalness_score = 5;</code>
     * @return float
     */
    public function getNaturalnessScore()
    {
        return isset($this->naturalness_score) ? $this->naturalness_score : 0.0;
    }

    public function hasNaturalnessScore()
    {
        return isset($this->naturalness_score);
    }

    public function clearNaturalnessScore()
    {
        unset($this->naturalness_score);
    }

    /**
     * needs the audio judge; judged 0-1: prosody / expressiveness
     *
     * Generated from protobuf field <code>optional float naturalness_score = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setNaturalnessScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->naturalness_score = $var;

        return $this;
    }

    /**
     * needs the audio judge; judged 0-1: key entities audibly intact
     *
     * Generated from protobuf field <code>optional float enunciation_score = 6;</code>
     * @return float
     */
    public function getEnunciationScore()
    {
        return isset($this->enunciation_score) ? $this->enunciation_score : 0.0;
    }

    public function hasEnunciationScore()
    {
        return isset($this->enunciation_score);
    }

    public function clearEnunciationScore()
    {
        unset($this->enunciation_score);
    }

    /**
     * needs the audio judge; judged 0-1: key entities audibly intact
     *
     * Generated from protobuf field <code>optional float enunciation_score = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setEnunciationScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->enunciation_score = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TTS::class, \Livekit\SimulationRun_JobMetrics_TTS::class);

