<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: livekit_agent_simulation.proto

namespace Livekit\SimulationRun\JobMetrics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Rows exist for text and audio;
 *
 * Generated from protobuf message <code>livekit.SimulationRun.JobMetrics.Turn</code>
 */
class Turn extends \Google\Protobuf\Internal\Message
{
    /**
     * 1-based, conversation order
     *
     * Generated from protobuf field <code>uint32 index = 1;</code>
     */
    protected $index = 0;
    /**
     * ASSISTANT — the agent under test, USER — simulator persona.
     *
     * Generated from protobuf field <code>.livekit.agent.ChatRole role = 2;</code>
     */
    protected $role = 0;
    /**
     * audio only; relative to t0; unset if the turn could not be aligned to the audio
     *
     * Generated from protobuf field <code>optional uint32 start_ms = 3;</code>
     */
    protected $start_ms = null;
    /**
     * audio only
     *
     * Generated from protobuf field <code>optional uint32 end_ms = 4;</code>
     */
    protected $end_ms = null;
    /**
     * Job groups hold means/pools of these; a field with no per-turn measurement stays unset here.
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.STT stt = 5;</code>
     */
    protected $stt = null;
    /**
     * ttft_ms, ttfs_ms, tokens_per_second, conciseness_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.LLM llm = 6;</code>
     */
    protected $llm = null;
    /**
     * ttfa_ms, ttfb_ms, naturalness_score, enunciation_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.TTS tts = 7;</code>
     */
    protected $tts = null;
    /**
     * response_latency_ms, agent_yield_latency_ms, agent_reported_e2e_latency_ms, 0/1 counts
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.Conversation conversation = 8;</code>
     */
    protected $conversation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $index
     *           1-based, conversation order
     *     @type int $role
     *           ASSISTANT — the agent under test, USER — simulator persona.
     *     @type int $start_ms
     *           audio only; relative to t0; unset if the turn could not be aligned to the audio
     *     @type int $end_ms
     *           audio only
     *     @type \Livekit\SimulationRun\JobMetrics\STT $stt
     *           Job groups hold means/pools of these; a field with no per-turn measurement stays unset here.
     *     @type \Livekit\SimulationRun\JobMetrics\LLM $llm
     *           ttft_ms, ttfs_ms, tokens_per_second, conciseness_score
     *     @type \Livekit\SimulationRun\JobMetrics\TTS $tts
     *           ttfa_ms, ttfb_ms, naturalness_score, enunciation_score
     *     @type \Livekit\SimulationRun\JobMetrics\Conversation $conversation
     *           response_latency_ms, agent_yield_latency_ms, agent_reported_e2e_latency_ms, 0/1 counts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LivekitAgentSimulation::initOnce();
        parent::__construct($data);
    }

    /**
     * 1-based, conversation order
     *
     * Generated from protobuf field <code>uint32 index = 1;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * 1-based, conversation order
     *
     * Generated from protobuf field <code>uint32 index = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkUint32($var);
        $this->index = $var;

        return $this;
    }

    /**
     * ASSISTANT — the agent under test, USER — simulator persona.
     *
     * Generated from protobuf field <code>.livekit.agent.ChatRole role = 2;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * ASSISTANT — the agent under test, USER — simulator persona.
     *
     * Generated from protobuf field <code>.livekit.agent.ChatRole role = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Livekit\Agent\ChatRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * audio only; relative to t0; unset if the turn could not be aligned to the audio
     *
     * Generated from protobuf field <code>optional uint32 start_ms = 3;</code>
     * @return int
     */
    public function getStartMs()
    {
        return isset($this->start_ms) ? $this->start_ms : 0;
    }

    public function hasStartMs()
    {
        return isset($this->start_ms);
    }

    public function clearStartMs()
    {
        unset($this->start_ms);
    }

    /**
     * audio only; relative to t0; unset if the turn could not be aligned to the audio
     *
     * Generated from protobuf field <code>optional uint32 start_ms = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStartMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->start_ms = $var;

        return $this;
    }

    /**
     * audio only
     *
     * Generated from protobuf field <code>optional uint32 end_ms = 4;</code>
     * @return int
     */
    public function getEndMs()
    {
        return isset($this->end_ms) ? $this->end_ms : 0;
    }

    public function hasEndMs()
    {
        return isset($this->end_ms);
    }

    public function clearEndMs()
    {
        unset($this->end_ms);
    }

    /**
     * audio only
     *
     * Generated from protobuf field <code>optional uint32 end_ms = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndMs($var)
    {
        GPBUtil::checkUint32($var);
        $this->end_ms = $var;

        return $this;
    }

    /**
     * Job groups hold means/pools of these; a field with no per-turn measurement stays unset here.
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.STT stt = 5;</code>
     * @return \Livekit\SimulationRun\JobMetrics\STT|null
     */
    public function getStt()
    {
        return $this->stt;
    }

    public function hasStt()
    {
        return isset($this->stt);
    }

    public function clearStt()
    {
        unset($this->stt);
    }

    /**
     * Job groups hold means/pools of these; a field with no per-turn measurement stays unset here.
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.STT stt = 5;</code>
     * @param \Livekit\SimulationRun\JobMetrics\STT $var
     * @return $this
     */
    public function setStt($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SimulationRun\JobMetrics\STT::class);
        $this->stt = $var;

        return $this;
    }

    /**
     * ttft_ms, ttfs_ms, tokens_per_second, conciseness_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.LLM llm = 6;</code>
     * @return \Livekit\SimulationRun\JobMetrics\LLM|null
     */
    public function getLlm()
    {
        return $this->llm;
    }

    public function hasLlm()
    {
        return isset($this->llm);
    }

    public function clearLlm()
    {
        unset($this->llm);
    }

    /**
     * ttft_ms, ttfs_ms, tokens_per_second, conciseness_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.LLM llm = 6;</code>
     * @param \Livekit\SimulationRun\JobMetrics\LLM $var
     * @return $this
     */
    public function setLlm($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SimulationRun\JobMetrics\LLM::class);
        $this->llm = $var;

        return $this;
    }

    /**
     * ttfa_ms, ttfb_ms, naturalness_score, enunciation_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.TTS tts = 7;</code>
     * @return \Livekit\SimulationRun\JobMetrics\TTS|null
     */
    public function getTts()
    {
        return $this->tts;
    }

    public function hasTts()
    {
        return isset($this->tts);
    }

    public function clearTts()
    {
        unset($this->tts);
    }

    /**
     * ttfa_ms, ttfb_ms, naturalness_score, enunciation_score
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.TTS tts = 7;</code>
     * @param \Livekit\SimulationRun\JobMetrics\TTS $var
     * @return $this
     */
    public function setTts($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SimulationRun\JobMetrics\TTS::class);
        $this->tts = $var;

        return $this;
    }

    /**
     * response_latency_ms, agent_yield_latency_ms, agent_reported_e2e_latency_ms, 0/1 counts
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.Conversation conversation = 8;</code>
     * @return \Livekit\SimulationRun\JobMetrics\Conversation|null
     */
    public function getConversation()
    {
        return $this->conversation;
    }

    public function hasConversation()
    {
        return isset($this->conversation);
    }

    public function clearConversation()
    {
        unset($this->conversation);
    }

    /**
     * response_latency_ms, agent_yield_latency_ms, agent_reported_e2e_latency_ms, 0/1 counts
     *
     * Generated from protobuf field <code>.livekit.SimulationRun.JobMetrics.Conversation conversation = 8;</code>
     * @param \Livekit\SimulationRun\JobMetrics\Conversation $var
     * @return $this
     */
    public function setConversation($var)
    {
        GPBUtil::checkMessage($var, \Livekit\SimulationRun\JobMetrics\Conversation::class);
        $this->conversation = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Turn::class, \Livekit\SimulationRun_JobMetrics_Turn::class);

